# Generated by Django 6.0.1 on 2026-01-28 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_quantity', models.IntegerField(default=0, help_text='可以销售的库存数量', verbose_name='可用库存')),
                ('frozen_quantity', models.IntegerField(default=0, help_text='订单占用的库存数量', verbose_name='冻结库存')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='products.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '商品库存',
                'verbose_name_plural': '商品库存',
                'db_table': 'product_stocks',
            },
        ),
    ]
