# Generated by Django 6.0.1 on 2026-02-05 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='remark',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_address',
        ),
        migrations.AddField(
            model_name='order',
            name='customer_name',
            field=models.CharField(default='', max_length=100, verbose_name='客户名称'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='customer_remark',
            field=models.TextField(blank=True, verbose_name='客户备注'),
        ),
    ]
