# Generated by Django 6.0.1 on 2026-01-28 07:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_status_alter_orderitem_cost_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_no', models.CharField(max_length=50, unique=True, verbose_name='支付单号')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='支付金额')),
                ('payment_method', models.CharField(help_text='例如：微信、支付宝、现金等', max_length=100, verbose_name='支付方式')),
                ('status', models.CharField(choices=[('pending', '待确认'), ('success', '支付成功'), ('failed', '支付失败')], default='pending', max_length=20, verbose_name='支付状态')),
                ('trade_no', models.CharField(blank=True, help_text='第三方支付平台的交易号', max_length=100, verbose_name='交易流水号')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_records', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='orders.order', verbose_name='订单')),
            ],
            options={
                'verbose_name': '支付记录',
                'verbose_name_plural': '支付记录',
                'db_table': 'payments',
                'indexes': [models.Index(fields=['-created_at'], name='payments_created_26b056_idx'), models.Index(fields=['order'], name='payments_order_i_b32b33_idx'), models.Index(fields=['status'], name='payments_status_d621e5_idx')],
            },
        ),
    ]
