"""
Django settings for warehouse_management project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-qfxwxu2b@-_y4p19fl%rb^d49+%p_hz$sq)ij4xhkzr!ofcxd6'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'simpleui',  # 必须放在 admin 之前
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # 第三方应用
    'rest_framework',
    'django_filters',
    'corsheaders',
    'ckeditor',
    'ckeditor_uploader',
    
    # 项目应用
    'apps.users',
    'apps.products',
    'apps.inventory',
    'apps.orders',
    'apps.cart',
    'apps.reports',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'warehouse_management.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'warehouse_management.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        'OPTIONS': {
            'timeout': 20,  # 数据库锁超时时间(秒)
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    # {
    #     'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    # },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# 自定义用户模型
AUTH_USER_MODEL = 'users.User'

# REST Framework 配置
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
}

# CORS 配置
CORS_ALLOW_ALL_ORIGINS = True  # 开发环境使用

# 默认主键类型
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# SimpleUI 配置
SIMPLEUI_HOME_INFO = False  # 隐藏首页的服务器信息
SIMPLEUI_ANALYSIS = False  # 关闭数据分析
SIMPLEUI_DEFAULT_THEME = 'admin.lte.css'  # 默认主题
SIMPLEUI_STATIC_OFFLINE = True  # 离线模式
SIMPLEUI_INDEX = '/admin/'  # 首页地址

# 管理后台配置
ADMIN_SITE_HEADER = '仓库管理系统'
ADMIN_SITE_TITLE = '仓库管理'
ADMIN_INDEX_TITLE = '欢迎使用仓库管理系统'

# SimpleUI 菜单配置
SIMPLEUI_CONFIG = {
    'system_keep': False,
    'menu_display': ['用户管理', '商品管理', '库存管理', '订单管理', '购物车'],
    'dynamic': True,
    'menus': [
        {
            'name': '用户管理',
            'icon': 'fas fa-users',
            'models': [
                {'name': '用户列表', 'icon': 'fas fa-user', 'url': 'users/user/'},
            ]
        },
        {
            'name': '商品管理',
            'icon': 'fas fa-box',
            'models': [
                {'name': '分类树结构', 'icon': 'fas fa-sitemap', 'url': 'products/category/tree/'},
                {'name': '商品分类', 'icon': 'fas fa-folder', 'url': 'products/category/'},
                {'name': '商品列表', 'icon': 'fas fa-cubes', 'url': 'products/product/'},
                {'name': '商品库存', 'icon': 'fas fa-boxes', 'url': 'products/productstock/'},
            ]
        },
        {
            'name': '库存管理',
            'icon': 'fas fa-warehouse',
            'models': [
                {'name': '供应商', 'icon': 'fas fa-truck', 'url': 'inventory/supplier/'},
                {'name': '入库记录', 'icon': 'fas fa-arrow-circle-down', 'url': 'inventory/stockin/'},
            ]
        },
        {
            'name': '订单管理',
            'icon': 'fas fa-shopping-cart',
            'models': [
                {'name': '订单列表', 'icon': 'fas fa-file-invoice', 'url': 'orders/order/'},
                {'name': '支付记录', 'icon': 'fas fa-money-bill-wave', 'url': 'orders/payment/'},
                {'name': '支付配置', 'icon': 'fas fa-credit-card', 'url': 'orders/paymentconfig/'},
            ]
        },
        {
            'name': '购物车',
            'icon': 'fas fa-cart-plus',
            'models': [
                {'name': '购物车列表', 'icon': 'fas fa-cart-arrow-down', 'url': 'cart/cart/'},
            ]
        },
    ]
}


# CKEditor 配置
CKEDITOR_UPLOAD_PATH = 'uploads/'
CKEDITOR_IMAGE_BACKEND = 'pillow'
CKEDITOR_CONFIGS = {
    'default': {
        'height': 300,
        'width': '100%',
        'toolbar': 'Custom',
        'toolbar_Custom': [
            ['Bold', 'Italic', 'Underline', 'Strike'],
            ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent'],
            ['Link', 'Unlink'],
            ['Image', 'Table'],
            ['RemoveFormat', 'Source'],
        ],
        'removePlugins': 'elementspath',
        'resize_enabled': False,
    },
}