# Generated by Django 6.0.1 on 2026-01-28 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(choices=[('add', '盘盈'), ('subtract', '盘亏'), ('damage', '损耗'), ('other', '其他')], max_length=20, verbose_name='调整类型')),
                ('quantity', models.IntegerField(verbose_name='调整数量')),
                ('before_stock', models.IntegerField(verbose_name='调整前库存')),
                ('after_stock', models.IntegerField(verbose_name='调整后库存')),
                ('reason', models.TextField(verbose_name='调整原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '库存调整',
                'verbose_name_plural': '库存调整',
                'db_table': 'stock_adjustments',
            },
        ),
        migrations.CreateModel(
            name='StockIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_in_no', models.CharField(max_length=50, unique=True, verbose_name='入库单号')),
                ('quantity', models.IntegerField(verbose_name='入库数量')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单位成本')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '入库记录',
                'verbose_name_plural': '入库记录',
                'db_table': 'stock_ins',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='供应商名称')),
                ('contact', models.CharField(blank=True, max_length=100, verbose_name='联系人')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('address', models.TextField(blank=True, verbose_name='地址')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '供应商',
                'verbose_name_plural': '供应商',
                'db_table': 'suppliers',
            },
        ),
    ]
