# Generated by Django 6.0.1 on 2026-01-28 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stockin',
            name='operator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_in_records', to=settings.AUTH_USER_MODEL, verbose_name='操作人'),
        ),
        migrations.AddField(
            model_name='stockin',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_ins', to='products.product', verbose_name='商品'),
        ),
        migrations.AddField(
            model_name='stockin',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_ins', to='inventory.supplier', verbose_name='供应商'),
        ),
        migrations.AddIndex(
            model_name='stockin',
            index=models.Index(fields=['-created_at'], name='stock_ins_created_ecaa3a_idx'),
        ),
        migrations.AddIndex(
            model_name='stockin',
            index=models.Index(fields=['product'], name='stock_ins_product_a8aa34_idx'),
        ),
        migrations.AddIndex(
            model_name='stockin',
            index=models.Index(fields=['supplier'], name='stock_ins_supplie_57c699_idx'),
        ),
    ]
