# Generated by Django 6.0.1 on 2026-01-28 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockAdjustment',
        ),
    ]
