# Generated by Django 6.0.1 on 2026-01-28 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_delete_stockadjustment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockin',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='留空则使用商品成本价', max_digits=10, null=True, verbose_name='单位成本'),
        ),
    ]
